# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.
#
# theme                  : "jekyll-theme-minimal"
remote_theme: "pages-themes/minimal@v0.2.0"
# plugins:
# - "jekyll-remote-theme"

# Site Settings
locale                    : "en-GB" # https://www.localeplanet.com/icu/iso639a/en-GB.html
lang                      : "en" # https://www.localeplanet.com/icu/iso639a/en.html
encoding                  : "utf-8"
title                     : "William Jawad"
title_separator           : "-"
name                      : "William Jawad"
description               : "A website to showcase studies and projects"
# keywords                 : # "keyword1, keyword2, keyword3"
logo                      : /assets/img/logo.png
subtitle                 : "test subtitle"
