# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.
#
# theme                  : "jekyll-theme-minimal"
remote_theme: "pages-themes/minimal@v0.2.0"
plugins:
  - "jekyll-remote-theme"

# Site Settings
locale                    : "en-GB" # https://www.localeplanet.com/icu/iso639a/en-GB.html
lang                      : "en" # https://www.localeplanet.com/icu/iso639a/en.html
encoding                  : "utf-8"
title                     : "William Jawad"
title_separator           : "-"
name                      : "William Jawad"
description               : "\n\nData Specialist with a background in Mechanical Engineering.
                              MSc in Artificial Intelligence (focus on Machine Learning,
                              and Deep Neural Networks) and experience in R&D,
                              predictive maintenance, and data engineering.
                              \n\n
                              Currently working as a Data Engineer at Aalto University in Finland.
                              Proficient in Python, T-SQL, and Azure,
                              with hands-on expertise in ETL optimisation,
                              SAS Viya, and agile product ownership.
                              Passionate about solving real-world problems
                              at the intersection of AI and industrial applications."
# keywords                 : # "keyword1, keyword2, keyword3"
logo                      : /assets/img/logo.png
subtitle                 : "test subtitle"
