# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.
#
# theme                  : "jekyll-theme-minimal"
remote_theme: "pages-themes/minimal@v0.2.0"
plugins:
  - "jekyll-remote-theme"

# Site Settings
locale                    : "en-GB" # https://www.localeplanet.com/icu/iso639a/en-GB.html
lang                      : "en" # https://www.localeplanet.com/icu/iso639a/en.html
encoding                  : "utf-8"
title                     : "William Jawad"
title_separator           : "-"
name                      : "William Jawad"
description               : "<br>Data Specialist with a background in Mechanical Engineering.
                              MSc in Artificial Intelligence (focus on Machine Learning,
                              and Deep Neural Networks) and experience in R&D,
                              predictive maintenance, and data engineering.
                              <br>
                              <br>
                              Currently working as a Data Engineer at Aalto University in Finland.
                              Proficient in Python, T-SQL, and Azure,
                              with hands-on expertise in ETL optimisation,
                              SAS Viya, and agile product ownership.
                              Passionate about solving real-world problems
                              at the intersection of AI and industrial applications."
# keywords                 : # "keyword1, keyword2, keyword3"
social_links:
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/williamjawad/"
  - name: "GitHub"
    url: "https://github.com/wiljav"
logo                      : /assets/img/logo.png
# subtitle                 : "test subtitle"
theme: "minima"
theme_color               : "#333"
# favicon                  : /assets/img/favicon.png
# favicon_color            : "#000000"
# logo_color               : "#000000"
logo_width              : 100
logo_height             : 100
# logo_alt                : "logo"
# logo_title              : "logo"
# logo_class              : "logo"
# logo_link               : "https://example.com"
# logo_link_target        : "_blank"
# logo_link_rel           : "noopener"
# logo_link_nofollow     : true
# logo_link_noopener     : true
# logo_link_noreferrer   : true